# Site settings
title: "IACR Elections 2022"
email: wee@di.ens.fr
description: > # this means to ignore newlines until "baseurl:"
baseurl: ""
url: "https://oui2wee.github.io"
# destination: _site

author :
  name : Hoeteck Wee
  email : wee@di.ens.fr

# Build settings
markdown: kramdown

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: none

# How many articles do you wish to appear on the front page:
# paginate: 3

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

